
language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 CXX=g++-9"
      compiler: g++

before_install:
  - sudo apt-get -y install git
  - mkdir spdlog
  - git clone https://github.com/gabime/spdlog.git spdlog
  - cd spdlog && mkdir build && cd build
  - cmake .. && make -j4 && make install
  - eval "${MATRIX_EVAL}"

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make -j4 && ./tests/tests
